// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type QuizioAnswer struct {
	IDAnswer   int32  `json:"id_answer"`
	Title      string `json:"title"`
	TkQuestion int32  `json:"tk_question"`
	IsCorrect  bool   `json:"is_correct"`
}

type QuizioAttempt struct {
	IDAttempt int32        `json:"id_attempt"`
	StartTime time.Time    `json:"start_time"`
	TimeTaken sql.NullTime `json:"time_taken"`
	TkQuiz    int32        `json:"tk_quiz"`
	TkUser    int32        `json:"tk_user"`
}

type QuizioAttemptQuestion struct {
	TkAttempt  int32 `json:"tk_attempt"`
	TkQuestion int32 `json:"tk_question"`
	TkAnswer   int32 `json:"tk_answer"`
}

type QuizioQuestion struct {
	IDQuestion int32   `json:"id_question"`
	Title      string  `json:"title"`
	Value      float64 `json:"value"`
	TkQuiz     int32   `json:"tk_quiz"`
}

type QuizioQuiz struct {
	IDQuiz      int32          `json:"id_quiz"`
	Title       string         `json:"title"`
	TimeLimit   int64          `json:"time_limit"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	PublishDate sql.NullTime   `json:"publish_date"`
	TkUser      int32          `json:"tk_user"`
	IsArchived  bool           `json:"is_archived"`
}

type QuizioUser struct {
	IDUser         int32          `json:"id_user"`
	Email          string         `json:"email"`
	IsAdmin        bool           `json:"is_admin"`
	Displayname    sql.NullString `json:"displayname"`
	Language       int32          `json:"language"`
	Theme          int32          `json:"theme"`
	ProfilePicture sql.NullString `json:"profile_picture"`
}
