// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const archiveQuiz = `-- name: ArchiveQuiz :one
UPDATE quizio."Quiz"
SET is_archived = $2
WHERE id_Quiz = $1
RETURNING id_Quiz,
	title,
	description,
	created_at,
	publish_date,
	tk_User,
	is_archived,
	EXTRACT(EPOCH FROM time_limit)::int AS time_limit_seconds
`

type ArchiveQuizParams struct {
	IDQuiz     int32 `json:"id_quiz"`
	IsArchived bool  `json:"is_archived"`
}

type ArchiveQuizRow struct {
	IDQuiz           int32          `json:"id_quiz"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	CreatedAt        time.Time      `json:"created_at"`
	PublishDate      sql.NullTime   `json:"publish_date"`
	TkUser           int32          `json:"tk_user"`
	IsArchived       bool           `json:"is_archived"`
	TimeLimitSeconds int32          `json:"time_limit_seconds"`
}

func (q *Queries) ArchiveQuiz(ctx context.Context, arg ArchiveQuizParams) (ArchiveQuizRow, error) {
	row := q.db.QueryRowContext(ctx, archiveQuiz, arg.IDQuiz, arg.IsArchived)
	var i ArchiveQuizRow
	err := row.Scan(
		&i.IDQuiz,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.PublishDate,
		&i.TkUser,
		&i.IsArchived,
		&i.TimeLimitSeconds,
	)
	return i, err
}

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO quizio."Answer" (title, tk_Question, is_correct)
VALUES ($1, $2, $3)
RETURNING id_Answer, title, tk_Question, is_correct
`

type CreateAnswerParams struct {
	Title      string `json:"title"`
	TkQuestion int32  `json:"tk_question"`
	IsCorrect  bool   `json:"is_correct"`
}

// Answers
func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (QuizioAnswer, error) {
	row := q.db.QueryRowContext(ctx, createAnswer, arg.Title, arg.TkQuestion, arg.IsCorrect)
	var i QuizioAnswer
	err := row.Scan(
		&i.IDAnswer,
		&i.Title,
		&i.TkQuestion,
		&i.IsCorrect,
	)
	return i, err
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO quizio."Attempt" (start_time, tk_Quiz, tk_User)
VALUES (NOW(), $1, $2)
RETURNING id_Attempt, start_time, time_taken, tk_Quiz, tk_User
`

type CreateAttemptParams struct {
	TkQuiz int32 `json:"tk_quiz"`
	TkUser int32 `json:"tk_user"`
}

// Attempts
func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (QuizioAttempt, error) {
	row := q.db.QueryRowContext(ctx, createAttempt, arg.TkQuiz, arg.TkUser)
	var i QuizioAttempt
	err := row.Scan(
		&i.IDAttempt,
		&i.StartTime,
		&i.TimeTaken,
		&i.TkQuiz,
		&i.TkUser,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO quizio."Question" (title, value, tk_Quiz)
VALUES ($1, $2, $3)
RETURNING id_Question, title, value, tk_Quiz
`

type CreateQuestionParams struct {
	Title  string  `json:"title"`
	Value  float64 `json:"value"`
	TkQuiz int32   `json:"tk_quiz"`
}

// Questions
func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (QuizioQuestion, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, arg.Title, arg.Value, arg.TkQuiz)
	var i QuizioQuestion
	err := row.Scan(
		&i.IDQuestion,
		&i.Title,
		&i.Value,
		&i.TkQuiz,
	)
	return i, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizio."Quiz" (
	title,
	time_limit,
	description,
	tk_User
)
VALUES ($1, make_interval(secs => $2), $3, $4)
RETURNING id_Quiz,
	title,
	description,
	created_at,
	publish_date,
	tk_User,
	is_archived,
	EXTRACT(EPOCH FROM time_limit)::int AS time_limit_seconds
`

type CreateQuizParams struct {
	Title       string         `json:"title"`
	Secs        float64        `json:"secs"`
	Description sql.NullString `json:"description"`
	TkUser      int32          `json:"tk_user"`
}

type CreateQuizRow struct {
	IDQuiz           int32          `json:"id_quiz"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	CreatedAt        time.Time      `json:"created_at"`
	PublishDate      sql.NullTime   `json:"publish_date"`
	TkUser           int32          `json:"tk_user"`
	IsArchived       bool           `json:"is_archived"`
	TimeLimitSeconds int32          `json:"time_limit_seconds"`
}

// Quizzes
func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (CreateQuizRow, error) {
	row := q.db.QueryRowContext(ctx, createQuiz,
		arg.Title,
		arg.Secs,
		arg.Description,
		arg.TkUser,
	)
	var i CreateQuizRow
	err := row.Scan(
		&i.IDQuiz,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.PublishDate,
		&i.TkUser,
		&i.IsArchived,
		&i.TimeLimitSeconds,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO quizio."User" (
	email,
	is_admin,
	displayName,
	language,
	theme,
	profile_picture
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id_User, email, is_admin, displayName, language, theme, profile_picture
`

type CreateUserParams struct {
	Email          string         `json:"email"`
	IsAdmin        bool           `json:"is_admin"`
	Displayname    sql.NullString `json:"displayname"`
	Language       int32          `json:"language"`
	Theme          int32          `json:"theme"`
	ProfilePicture sql.NullString `json:"profile_picture"`
}

// Users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (QuizioUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.IsAdmin,
		arg.Displayname,
		arg.Language,
		arg.Theme,
		arg.ProfilePicture,
	)
	var i QuizioUser
	err := row.Scan(
		&i.IDUser,
		&i.Email,
		&i.IsAdmin,
		&i.Displayname,
		&i.Language,
		&i.Theme,
		&i.ProfilePicture,
	)
	return i, err
}

const deleteAnswersByQuestion = `-- name: DeleteAnswersByQuestion :exec
DELETE FROM quizio."Answer"
WHERE tk_Question = $1
`

func (q *Queries) DeleteAnswersByQuestion(ctx context.Context, tkQuestion int32) error {
	_, err := q.db.ExecContext(ctx, deleteAnswersByQuestion, tkQuestion)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM quizio."Question"
WHERE id_Question = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, idQuestion int32) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, idQuestion)
	return err
}

const deleteQuiz = `-- name: DeleteQuiz :exec
DELETE FROM quizio."Quiz"
WHERE id_Quiz = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, idQuiz int32) error {
	_, err := q.db.ExecContext(ctx, deleteQuiz, idQuiz)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM quizio."User"
WHERE id_User = $1
`

func (q *Queries) DeleteUser(ctx context.Context, idUser int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, idUser)
	return err
}

const finalizeAttempt = `-- name: FinalizeAttempt :one
UPDATE quizio."Attempt" a
SET time_taken = LEAST(NOW() - a.start_time, q.time_limit)::time
FROM quizio."Quiz" q
WHERE a.id_Attempt = $1
	AND a.tk_Quiz = q.id_Quiz
	AND a.time_taken IS NULL
RETURNING a.id_Attempt, a.start_time, a.time_taken, a.tk_Quiz, a.tk_User
`

func (q *Queries) FinalizeAttempt(ctx context.Context, idAttempt int32) (QuizioAttempt, error) {
	row := q.db.QueryRowContext(ctx, finalizeAttempt, idAttempt)
	var i QuizioAttempt
	err := row.Scan(
		&i.IDAttempt,
		&i.StartTime,
		&i.TimeTaken,
		&i.TkQuiz,
		&i.TkUser,
	)
	return i, err
}

const finalizeAttemptIfExpired = `-- name: FinalizeAttemptIfExpired :one
UPDATE quizio."Attempt" a
SET time_taken = LEAST(NOW() - a.start_time, q.time_limit)::time
FROM quizio."Quiz" q
WHERE a.id_Attempt = $1
	AND a.tk_Quiz = q.id_Quiz
	AND a.time_taken IS NULL
	AND NOW() >= a.start_time + q.time_limit
RETURNING a.id_Attempt, a.start_time, a.time_taken, a.tk_Quiz, a.tk_User
`

func (q *Queries) FinalizeAttemptIfExpired(ctx context.Context, idAttempt int32) (QuizioAttempt, error) {
	row := q.db.QueryRowContext(ctx, finalizeAttemptIfExpired, idAttempt)
	var i QuizioAttempt
	err := row.Scan(
		&i.IDAttempt,
		&i.StartTime,
		&i.TimeTaken,
		&i.TkQuiz,
		&i.TkUser,
	)
	return i, err
}

const finalizeExpiredAttemptsForUser = `-- name: FinalizeExpiredAttemptsForUser :exec
UPDATE quizio."Attempt" a
SET time_taken = LEAST(NOW() - a.start_time, q.time_limit)::time
FROM quizio."Quiz" q
WHERE a.tk_User = $1
	AND a.tk_Quiz = q.id_Quiz
	AND a.time_taken IS NULL
	AND NOW() >= a.start_time + q.time_limit
`

func (q *Queries) FinalizeExpiredAttemptsForUser(ctx context.Context, tkUser int32) error {
	_, err := q.db.ExecContext(ctx, finalizeExpiredAttemptsForUser, tkUser)
	return err
}

const getAnswerForQuestion = `-- name: GetAnswerForQuestion :one
SELECT id_Answer, tk_Question
FROM quizio."Answer"
WHERE id_Answer = $1
	AND tk_Question = $2
`

type GetAnswerForQuestionParams struct {
	IDAnswer   int32 `json:"id_answer"`
	TkQuestion int32 `json:"tk_question"`
}

type GetAnswerForQuestionRow struct {
	IDAnswer   int32 `json:"id_answer"`
	TkQuestion int32 `json:"tk_question"`
}

func (q *Queries) GetAnswerForQuestion(ctx context.Context, arg GetAnswerForQuestionParams) (GetAnswerForQuestionRow, error) {
	row := q.db.QueryRowContext(ctx, getAnswerForQuestion, arg.IDAnswer, arg.TkQuestion)
	var i GetAnswerForQuestionRow
	err := row.Scan(&i.IDAnswer, &i.TkQuestion)
	return i, err
}

const getAttemptByUserQuiz = `-- name: GetAttemptByUserQuiz :one
SELECT id_Attempt, start_time, time_taken, tk_Quiz, tk_User
FROM quizio."Attempt"
WHERE tk_Quiz = $1
	AND tk_User = $2
`

type GetAttemptByUserQuizParams struct {
	TkQuiz int32 `json:"tk_quiz"`
	TkUser int32 `json:"tk_user"`
}

func (q *Queries) GetAttemptByUserQuiz(ctx context.Context, arg GetAttemptByUserQuizParams) (QuizioAttempt, error) {
	row := q.db.QueryRowContext(ctx, getAttemptByUserQuiz, arg.TkQuiz, arg.TkUser)
	var i QuizioAttempt
	err := row.Scan(
		&i.IDAttempt,
		&i.StartTime,
		&i.TimeTaken,
		&i.TkQuiz,
		&i.TkUser,
	)
	return i, err
}

const getAttemptWithQuiz = `-- name: GetAttemptWithQuiz :one
SELECT a.id_Attempt,
	a.start_time,
	a.time_taken,
	a.tk_Quiz,
	a.tk_User,
	(NOW() < a.start_time + q.time_limit) AS is_active,
	EXTRACT(EPOCH FROM q.time_limit)::int AS time_limit_seconds
FROM quizio."Attempt" a
JOIN quizio."Quiz" q ON q.id_Quiz = a.tk_Quiz
WHERE a.tk_Quiz = $1
	AND a.tk_User = $2
`

type GetAttemptWithQuizParams struct {
	TkQuiz int32 `json:"tk_quiz"`
	TkUser int32 `json:"tk_user"`
}

type GetAttemptWithQuizRow struct {
	IDAttempt        int32        `json:"id_attempt"`
	StartTime        time.Time    `json:"start_time"`
	TimeTaken        sql.NullTime `json:"time_taken"`
	TkQuiz           int32        `json:"tk_quiz"`
	TkUser           int32        `json:"tk_user"`
	IsActive         bool         `json:"is_active"`
	TimeLimitSeconds int32        `json:"time_limit_seconds"`
}

func (q *Queries) GetAttemptWithQuiz(ctx context.Context, arg GetAttemptWithQuizParams) (GetAttemptWithQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getAttemptWithQuiz, arg.TkQuiz, arg.TkUser)
	var i GetAttemptWithQuizRow
	err := row.Scan(
		&i.IDAttempt,
		&i.StartTime,
		&i.TimeTaken,
		&i.TkQuiz,
		&i.TkUser,
		&i.IsActive,
		&i.TimeLimitSeconds,
	)
	return i, err
}

const getQuestionQuizID = `-- name: GetQuestionQuizID :one
SELECT tk_Quiz
FROM quizio."Question"
WHERE id_Question = $1
`

func (q *Queries) GetQuestionQuizID(ctx context.Context, idQuestion int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getQuestionQuizID, idQuestion)
	var tk_quiz int32
	err := row.Scan(&tk_quiz)
	return tk_quiz, err
}

const getQuizByID = `-- name: GetQuizByID :one
SELECT id_Quiz,
	title,
	description,
	created_at,
	publish_date,
	tk_User,
	is_archived,
	EXTRACT(EPOCH FROM time_limit)::int AS time_limit_seconds
FROM quizio."Quiz"
WHERE id_Quiz = $1
`

type GetQuizByIDRow struct {
	IDQuiz           int32          `json:"id_quiz"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	CreatedAt        time.Time      `json:"created_at"`
	PublishDate      sql.NullTime   `json:"publish_date"`
	TkUser           int32          `json:"tk_user"`
	IsArchived       bool           `json:"is_archived"`
	TimeLimitSeconds int32          `json:"time_limit_seconds"`
}

func (q *Queries) GetQuizByID(ctx context.Context, idQuiz int32) (GetQuizByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getQuizByID, idQuiz)
	var i GetQuizByIDRow
	err := row.Scan(
		&i.IDQuiz,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.PublishDate,
		&i.TkUser,
		&i.IsArchived,
		&i.TimeLimitSeconds,
	)
	return i, err
}

const getQuizInfo = `-- name: GetQuizInfo :one
SELECT q.id_Quiz,
	q.title,
	q.description,
	q.created_at,
	q.publish_date,
	q.tk_User,
	q.is_archived,
	EXTRACT(EPOCH FROM q.time_limit)::int AS time_limit_seconds,
	COUNT(qq.id_Question)::int AS question_count
FROM quizio."Quiz" q
LEFT JOIN quizio."Question" qq ON qq.tk_Quiz = q.id_Quiz
WHERE q.id_Quiz = $1
GROUP BY q.id_Quiz
`

type GetQuizInfoRow struct {
	IDQuiz           int32          `json:"id_quiz"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	CreatedAt        time.Time      `json:"created_at"`
	PublishDate      sql.NullTime   `json:"publish_date"`
	TkUser           int32          `json:"tk_user"`
	IsArchived       bool           `json:"is_archived"`
	TimeLimitSeconds int32          `json:"time_limit_seconds"`
	QuestionCount    int32          `json:"question_count"`
}

func (q *Queries) GetQuizInfo(ctx context.Context, idQuiz int32) (GetQuizInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getQuizInfo, idQuiz)
	var i GetQuizInfoRow
	err := row.Scan(
		&i.IDQuiz,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.PublishDate,
		&i.TkUser,
		&i.IsArchived,
		&i.TimeLimitSeconds,
		&i.QuestionCount,
	)
	return i, err
}

const getQuizState = `-- name: GetQuizState :one
SELECT id_Quiz, tk_User, publish_date, is_archived
FROM quizio."Quiz"
WHERE id_Quiz = $1
`

type GetQuizStateRow struct {
	IDQuiz      int32        `json:"id_quiz"`
	TkUser      int32        `json:"tk_user"`
	PublishDate sql.NullTime `json:"publish_date"`
	IsArchived  bool         `json:"is_archived"`
}

func (q *Queries) GetQuizState(ctx context.Context, idQuiz int32) (GetQuizStateRow, error) {
	row := q.db.QueryRowContext(ctx, getQuizState, idQuiz)
	var i GetQuizStateRow
	err := row.Scan(
		&i.IDQuiz,
		&i.TkUser,
		&i.PublishDate,
		&i.IsArchived,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id_User, email, is_admin, displayName, language, theme, profile_picture
FROM quizio."User"
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (QuizioUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i QuizioUser
	err := row.Scan(
		&i.IDUser,
		&i.Email,
		&i.IsAdmin,
		&i.Displayname,
		&i.Language,
		&i.Theme,
		&i.ProfilePicture,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id_User, email, is_admin, displayName, language, theme, profile_picture
FROM quizio."User"
WHERE id_User = $1
`

func (q *Queries) GetUserByID(ctx context.Context, idUser int32) (QuizioUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, idUser)
	var i QuizioUser
	err := row.Scan(
		&i.IDUser,
		&i.Email,
		&i.IsAdmin,
		&i.Displayname,
		&i.Language,
		&i.Theme,
		&i.ProfilePicture,
	)
	return i, err
}

const listAnswersByQuestion = `-- name: ListAnswersByQuestion :many
SELECT id_Answer, title, tk_Question, is_correct
FROM quizio."Answer"
WHERE tk_Question = $1
ORDER BY id_Answer
`

func (q *Queries) ListAnswersByQuestion(ctx context.Context, tkQuestion int32) ([]QuizioAnswer, error) {
	rows, err := q.db.QueryContext(ctx, listAnswersByQuestion, tkQuestion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizioAnswer
	for rows.Next() {
		var i QuizioAnswer
		if err := rows.Scan(
			&i.IDAnswer,
			&i.Title,
			&i.TkQuestion,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedQuizzes = `-- name: ListArchivedQuizzes :many
SELECT q.id_Quiz,
	q.title,
	q.description,
	q.created_at,
	q.publish_date,
	q.tk_User,
	q.is_archived,
	EXTRACT(EPOCH FROM q.time_limit)::int AS time_limit_seconds,
	COUNT(qq.id_Question)::int AS question_count
FROM quizio."Quiz" q
LEFT JOIN quizio."Question" qq ON qq.tk_Quiz = q.id_Quiz
WHERE q.is_archived = TRUE
	AND ($1 = '' OR q.title ILIKE '%' || $1 || '%')
	AND ($2 = 0 OR q.tk_User = $2)
	AND ($3 = FALSE OR EXISTS (
		SELECT 1
		FROM quizio."Attempt" a
		WHERE a.tk_Quiz = q.id_Quiz
			AND a.tk_User = $4
	))
GROUP BY q.id_Quiz
ORDER BY q.created_at DESC
LIMIT $5 OFFSET $6
`

type ListArchivedQuizzesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	TkUser  int32       `json:"tk_user"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListArchivedQuizzesRow struct {
	IDQuiz           int32          `json:"id_quiz"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	CreatedAt        time.Time      `json:"created_at"`
	PublishDate      sql.NullTime   `json:"publish_date"`
	TkUser           int32          `json:"tk_user"`
	IsArchived       bool           `json:"is_archived"`
	TimeLimitSeconds int32          `json:"time_limit_seconds"`
	QuestionCount    int32          `json:"question_count"`
}

func (q *Queries) ListArchivedQuizzes(ctx context.Context, arg ListArchivedQuizzesParams) ([]ListArchivedQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedQuizzes,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.TkUser,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchivedQuizzesRow
	for rows.Next() {
		var i ListArchivedQuizzesRow
		if err := rows.Scan(
			&i.IDQuiz,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.PublishDate,
			&i.TkUser,
			&i.IsArchived,
			&i.TimeLimitSeconds,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptQuestions = `-- name: ListAttemptQuestions :many
SELECT tk_Attempt, tk_Question, tk_Answer
FROM quizio."Attempt_Question"
WHERE tk_Attempt = $1
`

func (q *Queries) ListAttemptQuestions(ctx context.Context, tkAttempt int32) ([]QuizioAttemptQuestion, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptQuestions, tkAttempt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizioAttemptQuestion
	for rows.Next() {
		var i QuizioAttemptQuestion
		if err := rows.Scan(&i.TkAttempt, &i.TkQuestion, &i.TkAnswer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinishedAttemptsByUser = `-- name: ListFinishedAttemptsByUser :many
SELECT id_Attempt, start_time, time_taken, tk_Quiz, tk_User
FROM quizio."Attempt"
WHERE tk_User = $1
	AND time_taken IS NOT NULL
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type ListFinishedAttemptsByUserParams struct {
	TkUser int32 `json:"tk_user"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFinishedAttemptsByUser(ctx context.Context, arg ListFinishedAttemptsByUserParams) ([]QuizioAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedAttemptsByUser, arg.TkUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizioAttempt
	for rows.Next() {
		var i QuizioAttempt
		if err := rows.Scan(
			&i.IDAttempt,
			&i.StartTime,
			&i.TimeTaken,
			&i.TkQuiz,
			&i.TkUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotPublishedQuizzes = `-- name: ListNotPublishedQuizzes :many
SELECT q.id_Quiz,
	q.title,
	q.description,
	q.created_at,
	q.publish_date,
	q.tk_User,
	q.is_archived,
	EXTRACT(EPOCH FROM q.time_limit)::int AS time_limit_seconds,
	COUNT(qq.id_Question)::int AS question_count
FROM quizio."Quiz" q
LEFT JOIN quizio."Question" qq ON qq.tk_Quiz = q.id_Quiz
WHERE q.is_archived = FALSE
	AND ($1 = '' OR q.title ILIKE '%' || $1 || '%')
	AND ($2 = 0 OR q.tk_User = $2)
	AND ($3 = FALSE OR EXISTS (
		SELECT 1
		FROM quizio."Attempt" a
		WHERE a.tk_Quiz = q.id_Quiz
			AND a.tk_User = $4
	))
GROUP BY q.id_Quiz
ORDER BY q.created_at DESC
LIMIT $5 OFFSET $6
`

type ListNotPublishedQuizzesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	TkUser  int32       `json:"tk_user"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListNotPublishedQuizzesRow struct {
	IDQuiz           int32          `json:"id_quiz"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	CreatedAt        time.Time      `json:"created_at"`
	PublishDate      sql.NullTime   `json:"publish_date"`
	TkUser           int32          `json:"tk_user"`
	IsArchived       bool           `json:"is_archived"`
	TimeLimitSeconds int32          `json:"time_limit_seconds"`
	QuestionCount    int32          `json:"question_count"`
}

func (q *Queries) ListNotPublishedQuizzes(ctx context.Context, arg ListNotPublishedQuizzesParams) ([]ListNotPublishedQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotPublishedQuizzes,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.TkUser,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotPublishedQuizzesRow
	for rows.Next() {
		var i ListNotPublishedQuizzesRow
		if err := rows.Scan(
			&i.IDQuiz,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.PublishDate,
			&i.TkUser,
			&i.IsArchived,
			&i.TimeLimitSeconds,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAttemptsByUser = `-- name: ListOpenAttemptsByUser :many
SELECT a.id_Attempt,
	a.start_time,
	a.time_taken,
	a.tk_Quiz,
	a.tk_User,
	EXTRACT(EPOCH FROM q.time_limit)::int AS time_limit_seconds
FROM quizio."Attempt" a
JOIN quizio."Quiz" q ON q.id_Quiz = a.tk_Quiz
WHERE a.tk_User = $1
	AND a.time_taken IS NULL
	AND NOW() < a.start_time + q.time_limit
ORDER BY a.start_time DESC
`

type ListOpenAttemptsByUserRow struct {
	IDAttempt        int32        `json:"id_attempt"`
	StartTime        time.Time    `json:"start_time"`
	TimeTaken        sql.NullTime `json:"time_taken"`
	TkQuiz           int32        `json:"tk_quiz"`
	TkUser           int32        `json:"tk_user"`
	TimeLimitSeconds int32        `json:"time_limit_seconds"`
}

func (q *Queries) ListOpenAttemptsByUser(ctx context.Context, tkUser int32) ([]ListOpenAttemptsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenAttemptsByUser, tkUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenAttemptsByUserRow
	for rows.Next() {
		var i ListOpenAttemptsByUserRow
		if err := rows.Scan(
			&i.IDAttempt,
			&i.StartTime,
			&i.TimeTaken,
			&i.TkQuiz,
			&i.TkUser,
			&i.TimeLimitSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedQuizzes = `-- name: ListPublishedQuizzes :many
SELECT q.id_Quiz,
	q.title,
	q.description,
	q.created_at,
	q.publish_date,
	q.tk_User,
	q.is_archived,
	EXTRACT(EPOCH FROM q.time_limit)::int AS time_limit_seconds,
	COUNT(qq.id_Question)::int AS question_count
FROM quizio."Quiz" q
LEFT JOIN quizio."Question" qq ON qq.tk_Quiz = q.id_Quiz
WHERE q.is_archived = FALSE
	AND q.publish_date IS NOT NULL
	AND q.publish_date <= NOW()
	AND ($1 = '' OR q.title ILIKE '%' || $1 || '%')
	AND ($2 = 0 OR q.tk_User = $2)
	AND ($3 = FALSE OR EXISTS (
		SELECT 1
		FROM quizio."Attempt" a
		WHERE a.tk_Quiz = q.id_Quiz
			AND a.tk_User = $4
	))
GROUP BY q.id_Quiz
ORDER BY q.publish_date DESC
LIMIT $5 OFFSET $6
`

type ListPublishedQuizzesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	TkUser  int32       `json:"tk_user"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListPublishedQuizzesRow struct {
	IDQuiz           int32          `json:"id_quiz"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	CreatedAt        time.Time      `json:"created_at"`
	PublishDate      sql.NullTime   `json:"publish_date"`
	TkUser           int32          `json:"tk_user"`
	IsArchived       bool           `json:"is_archived"`
	TimeLimitSeconds int32          `json:"time_limit_seconds"`
	QuestionCount    int32          `json:"question_count"`
}

func (q *Queries) ListPublishedQuizzes(ctx context.Context, arg ListPublishedQuizzesParams) ([]ListPublishedQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedQuizzes,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.TkUser,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedQuizzesRow
	for rows.Next() {
		var i ListPublishedQuizzesRow
		if err := rows.Scan(
			&i.IDQuiz,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.PublishDate,
			&i.TkUser,
			&i.IsArchived,
			&i.TimeLimitSeconds,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByQuiz = `-- name: ListQuestionsByQuiz :many
SELECT id_Question, title, value, tk_Quiz
FROM quizio."Question"
WHERE tk_Quiz = $1
ORDER BY id_Question
`

func (q *Queries) ListQuestionsByQuiz(ctx context.Context, tkQuiz int32) ([]QuizioQuestion, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsByQuiz, tkQuiz)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizioQuestion
	for rows.Next() {
		var i QuizioQuestion
		if err := rows.Scan(
			&i.IDQuestion,
			&i.Title,
			&i.Value,
			&i.TkQuiz,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setQuizPublishDate = `-- name: SetQuizPublishDate :one
UPDATE quizio."Quiz"
SET publish_date = $2
WHERE id_Quiz = $1
RETURNING id_Quiz,
	title,
	description,
	created_at,
	publish_date,
	tk_User,
	is_archived,
	EXTRACT(EPOCH FROM time_limit)::int AS time_limit_seconds
`

type SetQuizPublishDateParams struct {
	IDQuiz      int32        `json:"id_quiz"`
	PublishDate sql.NullTime `json:"publish_date"`
}

type SetQuizPublishDateRow struct {
	IDQuiz           int32          `json:"id_quiz"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	CreatedAt        time.Time      `json:"created_at"`
	PublishDate      sql.NullTime   `json:"publish_date"`
	TkUser           int32          `json:"tk_user"`
	IsArchived       bool           `json:"is_archived"`
	TimeLimitSeconds int32          `json:"time_limit_seconds"`
}

func (q *Queries) SetQuizPublishDate(ctx context.Context, arg SetQuizPublishDateParams) (SetQuizPublishDateRow, error) {
	row := q.db.QueryRowContext(ctx, setQuizPublishDate, arg.IDQuiz, arg.PublishDate)
	var i SetQuizPublishDateRow
	err := row.Scan(
		&i.IDQuiz,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.PublishDate,
		&i.TkUser,
		&i.IsArchived,
		&i.TimeLimitSeconds,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE quizio."Question"
SET title = $2,
		value = $3
WHERE id_Question = $1
RETURNING id_Question, title, value, tk_Quiz
`

type UpdateQuestionParams struct {
	IDQuestion int32   `json:"id_question"`
	Title      string  `json:"title"`
	Value      float64 `json:"value"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (QuizioQuestion, error) {
	row := q.db.QueryRowContext(ctx, updateQuestion, arg.IDQuestion, arg.Title, arg.Value)
	var i QuizioQuestion
	err := row.Scan(
		&i.IDQuestion,
		&i.Title,
		&i.Value,
		&i.TkQuiz,
	)
	return i, err
}

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE quizio."Quiz"
SET title = $2,
		description = $3,
		time_limit = make_interval(secs => $4)
WHERE id_Quiz = $1
RETURNING id_Quiz,
	title,
	description,
	created_at,
	publish_date,
	tk_User,
	is_archived,
	EXTRACT(EPOCH FROM time_limit)::int AS time_limit_seconds
`

type UpdateQuizParams struct {
	IDQuiz      int32          `json:"id_quiz"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Secs        float64        `json:"secs"`
}

type UpdateQuizRow struct {
	IDQuiz           int32          `json:"id_quiz"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	CreatedAt        time.Time      `json:"created_at"`
	PublishDate      sql.NullTime   `json:"publish_date"`
	TkUser           int32          `json:"tk_user"`
	IsArchived       bool           `json:"is_archived"`
	TimeLimitSeconds int32          `json:"time_limit_seconds"`
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (UpdateQuizRow, error) {
	row := q.db.QueryRowContext(ctx, updateQuiz,
		arg.IDQuiz,
		arg.Title,
		arg.Description,
		arg.Secs,
	)
	var i UpdateQuizRow
	err := row.Scan(
		&i.IDQuiz,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.PublishDate,
		&i.TkUser,
		&i.IsArchived,
		&i.TimeLimitSeconds,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE quizio."User"
SET displayName = $2
WHERE id_User = $1
RETURNING id_User, email, is_admin, displayName, language, theme, profile_picture
`

type UpdateUserDisplayNameParams struct {
	IDUser      int32          `json:"id_user"`
	Displayname sql.NullString `json:"displayname"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (QuizioUser, error) {
	row := q.db.QueryRowContext(ctx, updateUserDisplayName, arg.IDUser, arg.Displayname)
	var i QuizioUser
	err := row.Scan(
		&i.IDUser,
		&i.Email,
		&i.IsAdmin,
		&i.Displayname,
		&i.Language,
		&i.Theme,
		&i.ProfilePicture,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE quizio."User"
SET language = $2,
		theme = $3
WHERE id_User = $1
RETURNING id_User, email, is_admin, displayName, language, theme, profile_picture
`

type UpdateUserPreferencesParams struct {
	IDUser   int32 `json:"id_user"`
	Language int32 `json:"language"`
	Theme    int32 `json:"theme"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (QuizioUser, error) {
	row := q.db.QueryRowContext(ctx, updateUserPreferences, arg.IDUser, arg.Language, arg.Theme)
	var i QuizioUser
	err := row.Scan(
		&i.IDUser,
		&i.Email,
		&i.IsAdmin,
		&i.Displayname,
		&i.Language,
		&i.Theme,
		&i.ProfilePicture,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE quizio."User"
SET is_admin = $2
WHERE id_User = $1
RETURNING id_User, email, is_admin, displayName, language, theme, profile_picture
`

type UpdateUserRoleParams struct {
	IDUser  int32 `json:"id_user"`
	IsAdmin bool  `json:"is_admin"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (QuizioUser, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.IDUser, arg.IsAdmin)
	var i QuizioUser
	err := row.Scan(
		&i.IDUser,
		&i.Email,
		&i.IsAdmin,
		&i.Displayname,
		&i.Language,
		&i.Theme,
		&i.ProfilePicture,
	)
	return i, err
}

const upsertAttemptQuestion = `-- name: UpsertAttemptQuestion :exec
INSERT INTO quizio."Attempt_Question" (tk_Attempt, tk_Question, tk_Answer)
VALUES ($1, $2, $3)
ON CONFLICT (tk_Attempt, tk_Question)
DO UPDATE SET tk_Answer = EXCLUDED.tk_Answer
`

type UpsertAttemptQuestionParams struct {
	TkAttempt  int32 `json:"tk_attempt"`
	TkQuestion int32 `json:"tk_question"`
	TkAnswer   int32 `json:"tk_answer"`
}

func (q *Queries) UpsertAttemptQuestion(ctx context.Context, arg UpsertAttemptQuestionParams) error {
	_, err := q.db.ExecContext(ctx, upsertAttemptQuestion, arg.TkAttempt, arg.TkQuestion, arg.TkAnswer)
	return err
}
