-- MySQL Script generated by MySQL Workbench
-- Tue May 19 11:42:56 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id_User` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `is_admin` TINYINT NOT NULL DEFAULT 0,
  `displayName` VARCHAR(45) NULL,
  `language` INT NOT NULL DEFAULT 0,
  `theme` INT NOT NULL DEFAULT 0,
  `profile_picture` VARCHAR(255) NULL,
  PRIMARY KEY (`id_User`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `displayName_UNIQUE` (`displayName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Quiz` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Quiz` (
  `id_Quiz` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `time_limit` TIME NOT NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT 0,
  `publish_date` DATETIME NULL,
  `tk_User` INT NOT NULL,
  `is_archived` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_Quiz`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  INDEX `fk_Quiz_User1_idx` (`tk_User` ASC) VISIBLE,
  CONSTRAINT `fk_Quiz_User1`
    FOREIGN KEY (`tk_User`)
    REFERENCES `mydb`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `id_Question` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `value` FLOAT NOT NULL,
  `tk_Quiz` INT NOT NULL,
  PRIMARY KEY (`id_Question`),
  INDEX `fk_Vprasanje_Kviz_idx` (`tk_Quiz` ASC) VISIBLE,
  CONSTRAINT `fk_Vprasanje_Kviz`
    FOREIGN KEY (`tk_Quiz`)
    REFERENCES `mydb`.`Quiz` (`id_Quiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attempt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Attempt` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Attempt` (
  `id_Attempt` INT NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NOT NULL,
  `time_taken` TIME NULL,
  `tk_Quiz` INT NOT NULL,
  `tk_User` INT NOT NULL,
  PRIMARY KEY (`id_Attempt`),
  INDEX `fk_Attempt_Quiz1_idx` (`tk_Quiz` ASC) VISIBLE,
  INDEX `fk_Attempt_User1_idx` (`tk_User` ASC) VISIBLE,
  CONSTRAINT `fk_Attempt_Quiz1`
    FOREIGN KEY (`tk_Quiz`)
    REFERENCES `mydb`.`Quiz` (`id_Quiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attempt_User1`
    FOREIGN KEY (`tk_User`)
    REFERENCES `mydb`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Answer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `id_Answer` INT NOT NULL,
  `title` TEXT NOT NULL,
  `tk_Question` INT NOT NULL,
  `is_correct` TINYINT NOT NULL,
  PRIMARY KEY (`id_Answer`),
  INDEX `fk_Answer_Question1_idx` (`tk_Question` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`tk_Question`)
    REFERENCES `mydb`.`Question` (`id_Question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attempt_Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Attempt_Question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Attempt_Question` (
  `tk_Attempt` INT NOT NULL,
  `tk_Question` INT NOT NULL,
  `tk_Answer` INT NOT NULL,
  INDEX `fk_Attempt_Answer_Attempt1_idx` (`tk_Attempt` ASC) VISIBLE,
  INDEX `fk_Attempt_Answer_Question1_idx` (`tk_Question` ASC) VISIBLE,
  PRIMARY KEY (`tk_Attempt`, `tk_Question`),
  INDEX `fk_Attempt_Question_Answer1_idx` (`tk_Answer` ASC) VISIBLE,
  CONSTRAINT `fk_Attempt_Answer_Attempt1`
    FOREIGN KEY (`tk_Attempt`)
    REFERENCES `mydb`.`Attempt` (`id_Attempt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attempt_Answer_Question1`
    FOREIGN KEY (`tk_Question`)
    REFERENCES `mydb`.`Question` (`id_Question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attempt_Question_Answer1`
    FOREIGN KEY (`tk_Answer`)
    REFERENCES `mydb`.`Answer` (`id_Answer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
